web/src/Entity/Package.php
<?php

namespace App\Entity;

use App\Repository\PackageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Carbon\Carbon;

/**
 * @ORM\Entity(repositoryClass=PackageRepository::class)
 */
class Package implements \JsonSerializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description = '';

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $version = "";

    /**
     * @ORM\Column(type="text")
     */
    private $url = "";

    /**
     * @ORM\OneToMany(targetEntity=PackageRating::class, mappedBy="package")
     */
    private $ratings;

    /**
     * @ORM\ManyToMany(targetEntity=DeveloperGroup::class, mappedBy="packages")
     */
    private $developers;

    /**
     * @ORM\Column(type="integer")
     */
    private $downloads = 0;

    /**
     * @ORM\Column(type="float")
     */
    private $avg_rating = -1;

    /**
     * @ORM\OneToMany(targetEntity=PackageVersion::class, mappedBy="package", orphanRemoval=true)
     */
    private $versions;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $display_name;

    /**
     * @ORM\ManyToOne(targetEntity=PackageRepo::class, inversedBy="packages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $repo;

    /**
     * @ORM\ManyToMany(targetEntity=PackageTag::class, mappedBy="packages")
     */
    private $tags;

    public function __construct()
    {
        $this->ratings = new ArrayCollection();
        $this->developers = new ArrayCollection();
        $this->versions = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function jsonSerialize() {
        $res = [
            'id' => $this->id,
            'name' => $this->name,
            //'description' => $this->description,
            'url' => $this->url,
            'downloads' => $this->downloads,
            'avg_rating' => $this->avg_rating,
            'display_name' => $this->display_name,
            //'icon_url' => $this->icon_url,
            'versions' => [],
            'developers' => [],
            'tags' => [],
        ];

        $versions = $this->getVersions();
        foreach($versions as $version) {
            $res['versions'][] = $version->jsonSerialize();
        }

        $groups = $this->getDevelopers();
        foreach($groups as $group) {
            $res['developers'][] = $group->jsonSerialize();
        }

        $tags = $this->getTags();
        foreach($tags as $tag) {
            $res['tags'][] = $tag->getName();
        }

        return $res;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getVersion(): ?string
    {
        return $this->version;
    }

    public function setVersion(string $version): self
    {
        $this->version = $version;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    /**
     * @return Collection|PackageRating[]
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    public function addRating(PackageRating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setPackage($this);
        }

        return $this;
    }

    public function removeRating(PackageRating $rating): self
    {
        if ($this->ratings->contains($rating)) {
            $this->ratings->removeElement($rating);
            // set the owning side to null (unless already changed)
            if ($rating->getPackage() === $this) {
                $rating->setPackage(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|DeveloperGroup[]
     */
    public function getDevelopers(): Collection
    {
        return $this->developers;
    }

    public function addDeveloper(DeveloperGroup $developer): self
    {
        if (!$this->developers->contains($developer)) {
            $this->developers[] = $developer;
            $developer->addPackage($this);
        }

        return $this;
    }

    public function removeDeveloper(DeveloperGroup $developer): self
    {
        if ($this->developers->contains($developer)) {
            $this->developers->removeElement($developer);
            $developer->removePackage($this);
        }

        return $this;
    }

    public function getDownloads(): ?int
    {
        return $this->downloads;
    }

    public function setDownloads(int $downloads): self
    {
        $this->downloads = $downloads;

        return $this;
    }

    public function getAvgRating(): ?float
    {
        return $this->avg_rating;
    }

    public function setAvgRating(float $avg_rating): self
    {
        $this->avg_rating = $avg_rating;

        return $this;
    }

    /**
     * @return Collection|PackageVersion[]
     */
    public function getVersions(): Collection
    {
        return $this->versions;
    }

    public function getSpecificVersion(string $versionString) : ?PackageVersion
    {
        $versions = $this->getVersions();

        foreach ($versions as $version) {
            if ($version->getVersion() == $versionString) {
                return $version;
            }
        }

        //didn't find a match, return null
        return null;
    }

    public function getLatestVersion() : ?PackageVersion
    {
        if (empty($this->versions)) {
            return null;
        }

        //newest version should be last in the array
        return $this->versions[count($this->versions) - 1];
    }

    public function addVersion(PackageVersion $version): self
    {
        if (!$this->versions->contains($version)) {
            $this->versions[] = $version;
            $version->setPackage($this);
        }

        return $this;
    }

    public function removeVersion(PackageVersion $version): self
    {
        if ($this->versions->contains($version)) {
            $this->versions->removeElement($version);
            // set the owning side to null (unless already changed)
            if ($version->getPackage() === $this) {
                $version->setPackage(null);
            }
        }

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }

    public function getRepo(): ?PackageRepo
    {
        return $this->repo;
    }

    public function setRepo(?PackageRepo $repo): self
    {
        $this->repo = $repo;

        return $this;
    }

    /**
     * @return Collection|PackageTag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(PackageTag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addPackage($this);
        }

        return $this;
    }

    public function removeTag(PackageTag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
            $tag->removePackage($this);
        }

        return $this;
    }
}

web/src/Controller/UserController.php
<?php

namespace App\Controller;

use \DateTime;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

use App\Form\RegistrationType;
use App\Form\ChangePassType;
use App\Entity\User;

use App\Service\Mailer;
use App\Service\FileUploader;

class UserController extends AbstractController
{
    /**
     * @Route("/user/{id}", name="user_info")
     */
    public function userInfo(User $user)
    {
        return $this->render('user/userinfo.html.twig', [
            'controller_name' => 'UserController',
            'profile' => $user
        ]);
    }

    /**
     * @Route("/profile", name="profile", methods={"GET"})
     */
    public function profile()
    {
        $user = $this->getUser();

        $userJson = null;

        if ( !is_null($user) ) {
            $userJson = json_encode($user->userProfile());
        }

        return $this->render('user/profile.html.twig', [
            'userJson' => $userJson
        ]);
    }
}

web/templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}

{% block stylesheets %}
    {{ encore_entry_link_tags('user_profile') }}
{% endblock %}

{% block scripts %}
    {{ encore_entry_script_tags('user_profile') }}
{% endblock %}

{% block body %}
    <UserProfile userjson="{{ userJson }}"></UserProfile>
{% endblock %}

web/templates/user/recover.html.twig
{% extends 'base.html.twig' %}

{% import "include/forms.html.twig" as forms %}

{% block title %}Register{% endblock %}

{% block pageHeader %}{% endblock %}

{% block body %}
<style>
.col-inputs {
    border-left: 2px solid #C4C4C4;
}

.gc-input-group {
    margin-bottom: 2rem;
}

</style>
    {{ form_start(form) }}
        {{ form_errors(form) }}

        {% if error %}
            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}

        <div class="px-3">
            <div class="row mt-5 justify-content-center">
                <div class="col-auto">
                    <div class="container px-5">
                        <h4>Recover your Account password.</h4>
                        <div class="gc-input-group mt-5">
                            {{ form_errors(form.email) }}
                            {{ form_widget(form.email, { 'attr': {'class': 'form-control', 'placeholder': 'Email' } }) }}
                            <small class="form-text text-muted">{{ form_help(form.email) }}</small>
                        </div>

                        <button class="btn orange w-100 mt-5" type="submit">
                            Reset password
                        </button>
                    </div>
                </div>
            </div>
        </div>
    
    {{ form_end(form) }}
{% endblock %}

{% block scripts %}
{% endblock %}

web/templates/user/register.html.twig
{% extends 'base.html.twig' %}

{% import "include/forms.html.twig" as forms %}

{% block title %}Register{% endblock %}

{% block pageHeader %}{% endblock %}

{% block body %}
<style>
.col-inputs {
    border-left: 2px solid #C4C4C4;
}

.gc-input-group {
    margin-bottom: 2rem;
}

</style>
    {{ form_start(form) }}
        {{ form_errors(form) }}

        {% if error %}
            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
        {% endif %}

        <div class="px-3">
            <div class="row mt-5">
                <div class="col-md-6 mb-5">
                    <div class="row mt-5 mx-auto">
                        <div class="col-2">
                            <img src="/images/download.png">
                        </div>
                        <div class="col-10 pt-3">
                            <h4>View your download history</h4>
                        </div>
                    </div>
                    <div class="row mt-2 mx-auto">
                        <div class="col-2">
                            <img src="/images/feedback.png">
                        </div>
                        <div class="col-10 pt-3">
                            <h4>Get and give feedback</h4>
                        </div>
                    </div>
                    <div class="row mt-2 mx-auto">
                        <div class="col-2">
                            <img src="/images/package.png">
                        </div>
                        <div class="col-10 pt-3">
                            <h4>Manage packages</h4>
                        </div>
                    </div>
                    <div class="row mt-2 mx-auto">
                        <div class="col-2">
                            <img src="/images/notification.png">
                        </div>
                        <div class="col-10 pt-3">
                            <h4>Get update notifications</h4>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-inputs">
                    <div class="container px-5">
                        <h4>Find and download packages you need. It's always free.</h4>
                        <div class="gc-input-group mt-5">
                            {{ form_errors(form.email) }}
                            {{ form_widget(form.email, { 'attr': {'class': 'form-control', 'placeholder': 'Email' } }) }}
                            <small class="form-text text-muted">{{ form_help(form.email) }}</small>
                        </div>
                        <div class="gc-input-group">
                            {{ form_errors(form.display_name) }}
                            {{ form_widget(form.display_name, { 'attr': {'class': 'form-control', 'placeholder': 'Display Name' } }) }}
                            <small class="form-text text-muted">{{ form_help(form.display_name) }}</small>
                        </div>
                        <div class="gc-input-group">
                            {{ form_errors(form.full_name) }}
                            {{ form_widget(form.full_name, { 'attr': {'class': 'form-control', 'placeholder': 'Full Name' } }) }}
                            <small class="form-text text-muted">{{ form_help(form.full_name) }}</small>
                        </div>
                        <div class="gc-input-group">
                            {{ form_errors(form.location) }}
                            {{ form_widget(form.location, { 'attr': {'class': 'form-control', 'placeholder': 'Location' } }) }}
                            <small class="form-text text-muted">{{ form_help(form.location) }}</small>
                        </div>

                        <button class="btn orange w-100 mt-5" type="submit">
                            Create account
                        </button>
                        <p>Already have an account? <a href="/login">Sign in</a></p>
                    </div>
                </div>
            </div>
        </div>
    
    {{ form_end(form) }}
{% endblock %}

{% block scripts %}
{% endblock %}

web/templates/user/userinfo.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ profile.displayName }}{% endblock %}

{% block body %}
    <div class="container text-center pt-3">
        <p>{{ profile.displayName }}</p>
        <p>{{ profile.location }}</p>
    </div>
{% endblock %}